codecov:
  token: a61fdffb-2dde-4936-9b0e-0a54e8a9d1897

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
